<?php

namespace App\Enums;

enum PermissionKey: string
{
    case USERS_VIEW = 'USERS_VIEW';
    case USERS_CREATE = 'USERS_CREATE';
    case USERS_UPDATE = 'USERS_UPDATE';
    case USERS_DELETE = 'USERS_DELETE';
    case USERS_EXPORT = 'USERS_EXPORT';

    case PRODUCTS_VIEW = 'PRODUCTS_VIEW';
    case PRODUCTS_CREATE = 'PRODUCTS_CREATE';
    case PRODUCTS_UPDATE = 'PRODUCTS_UPDATE';
    case PRODUCTS_DELETE = 'PRODUCTS_DELETE';
    case PRODUCTS_EXPORT = 'PRODUCTS_EXPORT';

    case PROFILES_VIEW = 'PROFILES_VIEW';
    case PROFILES_CREATE = 'PROFILES_CREATE';
    case PROFILES_UPDATE = 'PROFILES_UPDATE';
    case PROFILES_DELETE = 'PROFILES_DELETE';
    case PROFILES_EXPORT = 'PROFILES_EXPORT';

    case SECTIONS_VIEW = 'SECTIONS_VIEW';
    case SECTIONS_CREATE = 'SECTIONS_CREATE';
    case SECTIONS_UPDATE = 'SECTIONS_UPDATE';
    case SECTIONS_DELETE = 'SECTIONS_DELETE';

    case AUDIT_LOGS_VIEW = 'AUDIT_LOGS_VIEW';
}
